{{- if and (include microcks.mongodb.username) (includ microcks.mongodb.password) (not (include microcks.mongodb.secretRef.secret)) }}
---
kind: Secret
apiVersion: v1
metadata:
  name: "{{ .Values.appName }}-mongodb-connection"
  labels:
    app: "{{ .Values.appName }}"
    container: mongodb
    group: microcks
type: kubernetes.io/basic-auth
stringData:
  username: "{{- include microcks.mongodb.username }}"
data:
  password: {{- include microcks.mongodb.password | b64enc | quote }}
{{- end }}


{{- if and (icnlude microcks.keycloak.username) (include microcks.keycloak.password) (not (include microcks.keycloak.secretRef.secret)) }}
---
kind: Secret
apiVersion: v1
metadata:
  name: "{{ .Values.appName }}-keycloak-admin"
  labels:
    app: "{{ .Values.appName }}"
    container: keycloak
    group: microcks
type: kubernetes.io/basic-auth
stringData:
  username: "{{- include microcks.keycloak.username -}}"
data:
  password: {{- include microcks.keycloak.password | b64enc | quote }}
{{- end }}