kind: Service
apiVersion: v1
metadata:
  name: "{{ .Values.appName }}"
  labels:
    app: "{{ .Values.appName }}"
    container: spring
    group: microcks
    {{- include "microcks-common-labels" . | nindent 4 }}
    {{- include "microcks-service-labels" . | nindent 4 }}
  annotations:
    {{- include "microcks-service-annotations" . | nindent 4 }}

spec:
  ports:
  - protocol: TCP
    port: {{ .Values.microcks.service.port }}
    targetPort: {{ .Values.microcks.service.targetPort }}
    name: spring
  type: {{ .Values.microcks.service.type | default "ClusterIP" | quote }}
  sessionAffinity: None
  selector:
    app: "{{ .Values.appName }}"
    container: spring
    group: microcks